import 'offline_first_model.dart';

/// Provider-agnostic adapter base for offline-first models.
///
/// Concrete subclasses (generated by `*_build` packages) implement
/// `fromRemote`/`toRemote` for their specific provider.
abstract class OfflineFirstAdapter<TModel extends OfflineFirstModel> {
  const OfflineFirstAdapter();
}
