import 'package:drift_offline_first/drift_offline_first.dart';

import 'models/offline_first_with_supabase_model.dart';

/// Base adapter for all offline-first Supabase models.
///
/// Subclasses are generated by `drift_offline_first_with_supabase_build`.
abstract class OfflineFirstWithSupabaseAdapter<TModel extends OfflineFirstWithSupabaseModel>
    extends OfflineFirstAdapter<TModel> {
  const OfflineFirstWithSupabaseAdapter();
}
