/// Describes how a Dart field maps to a Supabase column at runtime.
///
/// Generated by `drift_offline_first_with_supabase_build` and stored in each
/// adapter's `fieldsToSupabaseColumns` map.
class RuntimeSupabaseColumnDefinition {
  /// Whether this field is an association (i.e. another model).
  final bool association;

  /// The Supabase column name for this field.
  final String columnName;

  /// The Dart type of the associated model (set when [association] is true).
  final Type? associationType;

  /// Whether the association can be null.
  final bool associationIsNullable;

  /// The foreign key column on this model used to join the association.
  final String? foreignKey;

  /// Custom PostgREST query fragment overriding the generated one.
  final String? query;

  const RuntimeSupabaseColumnDefinition({
    required this.association,
    required this.columnName,
    this.associationType,
    this.associationIsNullable = false,
    this.foreignKey,
    this.query,
  });
}
