import 'package:drift_odoo_core/src/models/odoo_model.dart';

/// The glue between an [OdooModel] and the [OdooProvider].
///
/// Adapters are generated by `drift_offline_first_with_odoo_build`.
/// Each model annotated with `@ConnectOfflineFirstWithOdoo` gets its own adapter.
abstract class OdooAdapter<TModel extends OdooModel> {
  /// The Odoo technical model name (e.g. `'res.partner'`).
  String get odooModel;

  /// The fields to request from Odoo. Always includes `'id'` and `'write_date'`.
  List<String> get odooFields;

  const OdooAdapter();

  /// Deserialize an Odoo JSON record into [TModel].
  ///
  /// Note: Odoo returns `false` (not `null`) for empty fields.
  /// Adapters must handle this: `data['field'] == false ? null : data['field']`.
  Future<TModel> fromOdoo(
    Map<String, dynamic> data, {
    required covariant Object provider,
    covariant Object? repository,
  });

  /// Serialize [TModel] into an Odoo-compatible JSON map.
  ///
  /// The returned map is used as kwargs for `create` or `write`.
  /// The `id` field must NOT be included.
  Future<Map<String, dynamic>> toOdoo(
    TModel instance, {
    required covariant Object provider,
    covariant Object? repository,
  });
}
