import 'package:drift_odoo_core/src/models/odoo_model.dart';
import 'package:drift_odoo_core/src/odoo_adapter.dart';

/// Registry mapping [OdooModel] types to their [OdooAdapter]s.
///
/// Generated by `drift_offline_first_with_odoo_build` as `odooModelDictionary`.
class OdooModelDictionary {
  final Map<Type, OdooAdapter<OdooModel>> adapterFor;

  const OdooModelDictionary(this.adapterFor);
}
