import 'package:drift_odoo_core/drift_odoo_core.dart';
import 'package:drift_offline_first/drift_offline_first.dart';

import 'models/offline_first_with_odoo_model.dart';

/// Base adapter for all offline-first Odoo models.
///
/// Subclasses are generated by `drift_offline_first_with_odoo_build`.
abstract class OfflineFirstWithOdooAdapter<TModel extends OfflineFirstWithOdooModel>
    extends OfflineFirstAdapter<TModel> implements OdooAdapter<TModel> {
  const OfflineFirstWithOdooAdapter();
}
